export const DRAFT_WORK_ORDER_URL_REGULAR = '/work-orders/draft'

export const DRAFT_WORK_ORDER_URL_EXTERNAL = DRAFT_WORK_ORDER_URL_REGULAR

export const DRAFT_WORK_ORDER_URL_INTERNAL = `/api${DRAFT_WORK_ORDER_URL_EXTERNAL}`
